default: &default
  docker:
    - image: circleci/node:8.9.1
install_and_build: &install_and_build
  - restore_cache:
      keys:
        - checkout-{{ .Branch }}-{{ .Revision }}
  - restore_cache:
      keys:
        - yarn-cache-{{ checksum "package.json" }}
  - run:
      name: Install
      command: yarn install
  - save_cache:
      key: yarn-cache-{{ checksum "package.json" }}
      paths:
        - node_modules
  - run:
      name: Build
      command: yarn run build
version: 2
jobs:
  checkout:
    <<: *default
    working_directory: ~/tmp
    steps:
      - checkout
      - save_cache:
          key: checkout-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/tmp
  build:
    <<: *default
    working_directory: ~/tmp
    steps:
      *install_and_build
workflows:
  version: 2
  build-all:
    jobs:
      - checkout
      - build:
          requires:
            - checkout